modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/kosma/${mod_slug}-mod/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/${mod_slug}"
logoFile="${mod_slug}.png"
authors="${mod_vendor}, ${mod_author}"
description='''${mod_description}'''
displayTest="IGNORE_ALL_VERSION"
